source = $HOME/.config/hypr/wallust/wallust-hyprland.conf
$Scripts = $HOME/.config/hypr/scripts

general {
    no_fade_in = false
    no_fade_out = false
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    path = screenshot 
    blur_passes = 2 
    blur_size = 4
    noise = 0.02
    contrast = 1.1
    brightness = 0.5
}


image {
    monitor =
    path = /home/stopnope/ava.jpg
    size = 150
    rounding = -1
    border_size = 2
    border_color = rgba(89, 189, 166, 0.8) # Изумрудный неон
    rotate = 0
    reload_time = -1
    position = 0, 250
    halign = center
    valign = center
}


label {
    monitor =
    text = $TIME
    color = rgb(200, 200, 200)
    font_size = 120
    font_family = JetBrains Mono Nerd Font ExtraBold
    position = 0, 80
    halign = center
    valign = center
    shadow_passes = 2
}


label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A | %d %B")"
    color = rgba(89, 189, 166, 1.0)
    font_size = 20
    font_family = JetBrains Mono Nerd Font
    position = 0, -20
    halign = center
    valign = center
}


input-field {
    monitor =
    size = 300, 30
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.5
    dots_center = true
    
    inner_color = rgba(0, 0, 0, 0.0) # Прозрачное
    font_color = rgb(200, 200, 200)
    
    fade_on_empty = true
    placeholder_text = <span foreground="##59bda6">S Y S T E M _ L O C K E D</span>
    hide_input = false
    
    # Нижняя линия вместо рамки
    check_color = rgb(89, 189, 166)
    fail_color = rgb(204, 34, 34)
    
    position = 0, -200
    halign = center
    valign = center
}


label {
    monitor =
    text = cmd[update:60000] echo "UPTIME: $( $Scripts/Uptimehm.sh)"
    color = rgba(255, 255, 255, 0.4)
    font_size = 10
    font_family = JetBrains Mono Nerd Font
    position = 20, 20
    halign = left
    valign = bottom
}


label {
    monitor =
    text = cmd[update:3600000] echo "$(/home/stopnope/.config/hypr/scripts/weather.sh)"
    color = rgba(255, 255, 255, 0.4)
    font_size = 10
    font_family = JetBrains Mono Nerd Font
    position = -20, 20
    halign = right
    valign = bottom
}
