# --- HYPRLAND MAIN CONFIG ---
# Optimized for NVIDIA GTX 1070 Ti
# --- MONITORS ---
monitor=,1920x1080@180,auto,1
# --- ENV VARIABLES (NVIDIA FIXES) ---
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = __GL_GSYNC_ALLOWED,0
env = __GL_VRR_ALLOWED,0
env = NVD_BACKEND,direct
env = WLR_DRM_DEVICES,/dev/drm/card1
# --- CURSOR ---
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Classic

render {
    direct_scanout = false 
}

cursor {
    no_hardware_cursors = true
}

# --- INPUT ---
input {
kb_layout = us,ru
kb_options = grp:alt_shift_toggle
follow_mouse = 1
sensitivity = 0
}
# --- LOOK & FEEL ---
general {
    gaps_in = 3
    gaps_out = 10
    border_size = 0         # Убираем обводку совсем
    layout = dwindle
}

decoration {
    rounding = 10

    
    active_opacity = 0.95
    inactive_opacity = 0.85  
    fullscreen_opacity = 1.0

    blur {
        enabled = false 
        }

    shadow {
        enabled = false     
    }
}

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = fluent_decel, 0.1, 1, 0, 1
    bezier = easeInOutCirc, 0.85, 0, 0.15, 1
    bezier = shot, 0.2, 1, 0.2, 1
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = bounce, 0.2, 1.2, 0.2, 1
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
    animation = windows, 1, 8, bounce, popin 80%
    
    
    animation = windowsOut, 1, 7, winOut, popin 80%
    
    
    animation = windowsMove, 1, 8, wind, slide
    
    
    animation = workspaces, 1, 8, bounce, slide
    
    
    animation = fade, 1, 8, default
}
# --- SOURCING KEYBINDINGS ---
source = ~/.config/hypr/keybindings.conf
# --- AUTOSTART ---
exec-once = waybar
exec-once = hyprpaper
exec-once = bash -c "sleep 2 && awww-daemon"
exec-once = bash -c "sleep 3 && ~/.config/hypr/scripts/wall.sh"
exec-onec = mako
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprpm reload -n
exec-once = hyprswitch init &
exec-once = hyprctl plugin load /home/stopnope/.local/share/hyprpm/Hyprspace/Hyprspace.so






misc {
    #vfr = false
    always_follow_on_dnd = true
    layers_hog_keyboard_focus = true
    animate_manual_resizes = false
}
